server:
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        # nombre de nuestro route
        - id: nttdatacentersspringt5AHS
          # uri lo redirijimos a nuestros service costumer service (nombre que esta registrado eureka server)
          uri: lb://nttdatacentersspringt5AHS
          #filtro que va a aplicar al path de la llamada de nuestros microservicios (todo lo que lleva costumers)
          predicates:
            - Path=/api/**